services:
  db:
    image: postgres:16
    container_name: things-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: things
    ports:
      - "5432:5432"
    volumes:
      - things_pg:/var/lib/postgresql/data

volumes:
  things_pg:
